### ISSUE TITLE
update/replace SSL Cert

### ISSUE THREAD

**Issue by kgorman** [rackerlabs/developer.rackspace.com#1018]
developer.rackspace.com appears to have a rewrite rule for enforcing HTTPS for all connections, thus sub-domains like mysql.rackspace.com, mongodb.rackspace.com, etc all need to be added to the cert, or perhaps we could forgo the SSL connection for these? Is there a reason SSL is needed for this? It's just static pages...

**Comment by kenperkins** [comment]
See commentary from earlier: 

https://github.com/rackerlabs/developer.rackspace.com/issues/306

**Comment by kenperkins** [comment]
This appears no longer relevant with our migration to deconst. Closing.
