### ISSUE TITLE
update Community drop-down menu to reflect changes to sponsorship page

### ISSUE THREAD

**Issue by danabauer** [rackerlabs/developer.rackspace.com#1071]
![community-drop-down](https://cloud.githubusercontent.com/assets/751594/6311009/cdfa9e10-b92a-11e4-8553-49342fdf55b7.png)

The Community drop-down menu has a "Request a sponsorship" option that we need to change now that we've removed the sponsorship form. 

Suggestions for new option:
- OSS & sponsorships
- Contributions
- OSS contributions
- Support & sponsorships

Thoughts, @kenperkins?

**Comment by kenperkins** [comment]
more ideas

- Outreach
- Outreach & Events
- Programs & Events

**Comment by danabauer** [comment]
let's go with Outreach & Events

**Comment by ChristieQ** [comment]
I agree with "Outreach & Events"

**Comment by danabauer** [comment]
Thanks, @ChristieQ!

**Comment by danabauer** [comment]
@ChristieQ Ken suggests that you edit it in VWO for now. Can you make the Outreach & Events change there?

**Comment by danabauer** [comment]
![new-nav](https://cloud.githubusercontent.com/assets/751594/6330363/8fb649b6-bb45-11e4-91d2-3cc48cd8088b.png)
 VWO temporarily disabled. New nav is in place with Outreach & Events
