### ISSUE TITLE
Header takes up too much space on some mobiles

### ISSUE THREAD

**Issue by rgbkrk** [rackerlabs/developer.rackspace.com#1110]
With the addition of Facebook's viewing headers, there's almost no screen real estate for consuming content.

![ios_ugly_facebook_view](https://cloud.githubusercontent.com/assets/836375/6902936/3ccb4ab2-d6d4-11e4-9a71-6a20878f59de.png)

**Comment by smashwilson** [comment]
@rgbkrk care to check this out again when you get the chance? I just unborked the build :walking:

**Comment by rgbkrk** [comment]
Yup, header no longer sticky. Flows like a piece of static content.
