### ISSUE TITLE
Links to Developer Blog posts on main page are broken

### ISSUE THREAD

**Issue by danabauer** [rackerlabs/developer.rackspace.com#1117]
Links take user back to top of main page. Not a 404. 
![dev-blog-links](https://cloud.githubusercontent.com/assets/751594/6999072/ad427444-dbc7-11e4-84f2-ee374715b86a.png)

Chrome and Firefox on OSX

**Comment by ycombinator** [comment]
Same for Product News links (to the right of Developer Blog links).

**Comment by ycombinator** [comment]
Looks like these links are just hardcoded, static content: https://github.com/rackerlabs/developer.rackspace.com/blob/master/src/site_source/index.html#L112-L137
