### ISSUE TITLE
Datacenters are inaccurate

### ISSUE THREAD

**Issue by linuxman1000** [rackerlabs/developer.rackspace.com#1160]
https://developer.rackspace.com/docs/cloud-databases/getting-started/#authentication

The list of regions (below) is inaccurate:

(from the page above):
You may specify a default region as well. Here is a list of available regions:

DFW (Chicago, IL, US)
HKG (Hong Kong, China)
IAD (Blacksburg, VA, US)
LON (London, England)
SYD (Sydney, Australia)

DFW is Dallas
ORD is Chicago but not included

**Comment by rgbkrk** [comment]
Wow DFW being listed as Chicago is pretty wrong.

If I had to guess, ORD wasn't listed because the ORD region isn't available to new customers. We'll check on that one.

We also need to update the URL that this

**Comment by rgbkrk** [comment]
Fixed in https://github.com/rackerlabs/docs-quickstart/pull/5 (the new location for this content).
