### ISSUE TITLE
Add pricing info for MI for developer+ customers on FAQ

### ISSUE THREAD

**Issue by danabauer** [rackerlabs/developer.rackspace.com#1162]
The first dev+ customers are transitioning to MI by July 31. Add new pricing info to FAQ page. 
https://developer.rackspace.com/developer-plus/faq/

For example, you were running a single General Purpose 4GB Cloud Server for an entire month (730 hours) on your account, you will see the following change:

Last invoice (before discount expires): 
General Purpose 4GB Linux Server (730 hrs): $93.34
Developer+ Discount: -$50
*Invoice total: $43.34*

New invoice (after discount expires):
General Purpose 4GB Linux Server (730 hrs): $93.34
Managed Infrastructure Service Level minimum: $50
*Invoice total: $143.34*

**Comment by kenperkins** [comment]
This won't be done in the d.r.c. repo, but rather the https://github.com/rackerlabs/docs-developer-blog repository, FYI.

**Comment by danabauer** [comment]
@kenperkins ok, I'll close this issue are reopen in the other repo
