### ISSUE TITLE
Link to "Neutron Networking: Simple Flat Network" is broken and does not exist anymore

### ISSUE THREAD

**Issue by nmadhok** [rackerlabs/developer.rackspace.com#1164]
Link to "Neutron Networking: Simple Flat Network" does not exist on the page https://developer.rackspace.com/blog/neutron-networking-vlan-provider-networks/ anymore. When I visit the link, I get Page not found error (https://developer.rackspace.com/blog/neutron-networking-simple-flat-network.html)

Also, the ``<!-- more -->`` tag is visible

<img width="1440" alt="screen shot 2015-07-04 at 5 45 12 am" src="https://cloud.githubusercontent.com/assets/3374962/8507412/f182e7b8-220f-11e5-9f9d-760345f9407d.png">

**Comment by ktbartholomew** [comment]
Moved to [rackerlabs/nexus-control#45](https://github.com/rackerlabs/nexus-control/issues/45)
