### ISSUE TITLE
Atom feed looks malformed

### ISSUE THREAD

**Issue by major** [rackerlabs/developer.rackspace.com#1165]
If I try to access https://developer.rackspace.com/atom.xml I get a redirect over to https://developer.rackspace.com/atom.xml/ but the RSS/Atom feed looks to be malformed.  There's a bunch of HTML wrapped around it.  My RSS feed reader can't read the feed.

**Comment by ktbartholomew** [comment]
Duplicated to https://github.com/deconst/deconst-docs/issues/120
