### ISSUE TITLE
Unable to download the pom.xml file from SDKs page

### ISSUE THREAD

**Issue by johannby** [rackerlabs/developer.rackspace.com#1166]
Hello,

I've tried to download/open the pom.xml file for Maven from Java section from https://developer.rackspace.com/sdks/ . The latest versions of IE and Google Chrome open a new page with content of the file inlined to the body of the page instead of simple download. Possibly it works as designed but in the same time the page doesn't shows a structure of the POM, it shows only the content from-inside xml tags.

Here is an example how browsers show the page:
![image](https://cloud.githubusercontent.com/assets/411577/8797739/1d3ef98e-2fa6-11e5-9843-0893cb036c93.png)

Thanks,

Best regards,
Ivan Bileychik

**Comment by ktbartholomew** [comment]
Thanks for reporting this, it should be fixed today!
