### ISSUE TITLE
Figure out how to get title from Sphinx doc plumbed into Jekyll front-matter

### ISSUE THREAD

**Issue by kenperkins** [rackerlabs/developer.rackspace.com#205]
If we want to be able to put some interesting text from a sphinx doc into the layout rendered by Jekyll (for example, the big blue bar) we need a way to plumb that data up somewhere.

This is why all of the docs pages currently just say "Rackspace Developer Center" for both html->head->title and in the big blue bar.

**Comment by kenperkins** [comment]
@ktbartholomew I think we don't need this anymore yea?

**Comment by ktbartholomew** [comment]
definitely not.
